/*
 * generated by Xtext 2.12.0
 */
package org.xtext.roqmemapping


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class RoQMEMappingStandaloneSetup extends RoQMEMappingStandaloneSetupGenerated {

	def static void doSetup() {
		new RoQMEMappingStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
