/*
 * generated by Xtext 2.12.0
 */
package org.xtext.roqmemapping.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRoQMEMappingScopeProvider extends DelegatingScopeProvider {
}
