//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMROQMEESTIMATE_ROQMEESTIMATE_H_
#define COMMROQMEESTIMATE_ROQMEESTIMATE_H_

#include "CommRoqmeEstimate/RoqmeEstimateCore.hh"

namespace CommRoqmeEstimate {
		
class RoqmeEstimate : public RoqmeEstimateCore {
	public:
		// default constructors
		RoqmeEstimate();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// RoqmeEstimate(const std::string &name, const double &value);
		
		RoqmeEstimate(const RoqmeEstimateCore &roqmeEstimate);
		RoqmeEstimate(const DATATYPE &roqmeEstimate);
		virtual ~RoqmeEstimate();
		
		// use framework specific getter and setter methods from core (base) class
		using RoqmeEstimateCore::get;
		using RoqmeEstimateCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const RoqmeEstimate &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommRoqmeEstimate */
#endif /* COMMROQMEESTIMATE_ROQMEESTIMATE_H_ */
