/**
 * generated by Xtext 2.12.0
 */
package org.xtext.roqmemapping.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.roqmemapping.RoQMEMappingRuntimeModule;
import org.xtext.roqmemapping.RoQMEMappingStandaloneSetup;
import org.xtext.roqmemapping.ide.RoQMEMappingIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class RoQMEMappingIdeSetup extends RoQMEMappingStandaloneSetup {
  @Override
  public Injector createInjector() {
    RoQMEMappingRuntimeModule _roQMEMappingRuntimeModule = new RoQMEMappingRuntimeModule();
    RoQMEMappingIdeModule _roQMEMappingIdeModule = new RoQMEMappingIdeModule();
    return Guice.createInjector(Modules2.mixin(_roQMEMappingRuntimeModule, _roQMEMappingIdeModule));
  }
}
