/**
 * generated by Xtext 2.12.0
 */
package org.xtext.roqmemapping.ide;

import org.xtext.roqmemapping.ide.AbstractRoQMEMappingIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RoQMEMappingIdeModule extends AbstractRoQMEMappingIdeModule {
}
