/*
 * generated by Xtext 2.12.0
 */
package org.xtext.roqme.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.roqme.parser.antlr.internal.InternalRoQMEParser;
import org.xtext.roqme.services.RoQMEGrammarAccess;

public class RoQMEParser extends AbstractAntlrParser {

	@Inject
	private RoQMEGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRoQMEParser createParser(XtextTokenStream stream) {
		return new InternalRoQMEParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "RoqmeModel";
	}

	public RoQMEGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RoQMEGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
