/*
 * generated by Xtext 2.12.0
 */
package org.xtext.roqme.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRoQMEScopeProvider extends DelegatingScopeProvider {
}
