/*
 * generated by Xtext 2.12.0
 */
package org.xtext.roqme.ide

import com.google.inject.Guice
import org.eclipse.xtext.util.Modules2
import org.xtext.roqme.RoQMERuntimeModule
import org.xtext.roqme.RoQMEStandaloneSetup

/**
 * Initialization support for running Xtext languages as language servers.
 */
class RoQMEIdeSetup extends RoQMEStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new RoQMERuntimeModule, new RoQMEIdeModule))
	}
	
}
