/**
 * generated by Xtext 2.12.0
 */
package org.xtext.roqme.formatting2;

import com.google.inject.Inject;
import java.util.Arrays;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.formatting2.AbstractFormatter2;
import org.eclipse.xtext.formatting2.IFormattableDocument;
import org.eclipse.xtext.resource.XtextResource;
import org.eclipse.xtext.xbase.lib.Extension;
import org.xtext.roqme.services.RoQMEGrammarAccess;
import roqme.metamodel.datatypes.DataTypeDeclaration;
import roqme.metamodel.datatypes.DataTypeDefinition;
import roqme.metamodel.datatypes.RoqmeModel;
import roqme.metamodel.datatypes.Sentence;
import roqme.metamodel.datatypes.TypedVariable;
import roqme.metamodel.kernel.PrimitiveContext;

@SuppressWarnings("all")
public class RoQMEFormatter extends AbstractFormatter2 {
  @Inject
  @Extension
  private RoQMEGrammarAccess _roQMEGrammarAccess;
  
  protected void _format(final RoqmeModel roqmeModel, @Extension final IFormattableDocument document) {
    EList<Sentence> _sentences = roqmeModel.getSentences();
    for (final Sentence sentence : _sentences) {
      document.<Sentence>format(sentence);
    }
    EList<DataTypeDefinition> _dataTypes = roqmeModel.getDataTypes();
    for (final DataTypeDefinition dataTypeDefinition : _dataTypes) {
      document.<DataTypeDefinition>format(dataTypeDefinition);
    }
    EList<TypedVariable> _variables = roqmeModel.getVariables();
    for (final TypedVariable typedVariable : _variables) {
      document.<TypedVariable>format(typedVariable);
    }
  }
  
  protected void _format(final PrimitiveContext primitiveContext, @Extension final IFormattableDocument document) {
    document.<DataTypeDeclaration>format(primitiveContext.getDeclaration());
  }
  
  public void format(final Object primitiveContext, final IFormattableDocument document) {
    if (primitiveContext instanceof PrimitiveContext) {
      _format((PrimitiveContext)primitiveContext, document);
      return;
    } else if (primitiveContext instanceof XtextResource) {
      _format((XtextResource)primitiveContext, document);
      return;
    } else if (primitiveContext instanceof RoqmeModel) {
      _format((RoqmeModel)primitiveContext, document);
      return;
    } else if (primitiveContext instanceof EObject) {
      _format((EObject)primitiveContext, document);
      return;
    } else if (primitiveContext == null) {
      _format((Void)null, document);
      return;
    } else if (primitiveContext != null) {
      _format(primitiveContext, document);
      return;
    } else {
      throw new IllegalArgumentException("Unhandled parameter types: " +
        Arrays.<Object>asList(primitiveContext, document).toString());
    }
  }
}
