/**
 * generated by Xtext 2.12.0
 */
package org.xtext.roqmemapping;

import org.xtext.roqmemapping.RoQMEMappingStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class RoQMEMappingStandaloneSetup extends RoQMEMappingStandaloneSetupGenerated {
  public static void doSetup() {
    new RoQMEMappingStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
