/*
 * generated by Xtext 2.12.0
 */
package org.xtext.roqme.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;
import org.eclipse.xtext.validation.ComposedChecks;
import org.eclipse.xtext.validation.NamesAreUniqueValidator;

@ComposedChecks(validators = {NamesAreUniqueValidator.class})
public abstract class AbstractRoQMEValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(EPackage.Registry.INSTANCE.getEPackage("https://robmosys.eu/roqme/datatypes"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("https://robmosys.eu/roqme/kernel"));
		result.add(EPackage.Registry.INSTANCE.getEPackage("https://robmosys.eu/roqme/expressions"));
		return result;
	}
	
}
