/**
 * generated by Xtext 2.12.0
 */
package org.xtext.roqme.ide;

import org.xtext.roqme.ide.AbstractRoQMEIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class RoQMEIdeModule extends AbstractRoQMEIdeModule {
}
