/*
 * generated by Xtext 2.12.0
 */
package org.xtext.roqmemapping.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RoQMEMappingAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/roqmemapping/parser/antlr/internal/InternalRoQMEMapping.tokens");
	}
}
